# -*- coding: utf-8 -*-
"""classification_model -all tickets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r8zod0TCKXTR3D9ql7JoPAxbOhcrs32k
"""

import pandas as pd
import zipfile

# ML
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

zip_path = "all_tickets_processed_improved_v3.csv.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall()

df = pd.read_csv("all_tickets_processed_improved_v3.csv")

print(df.head())

print(df.columns)

df.dropna(inplace=True)

X = df['Document']        # text column
y = df['Topic_group']    # label column

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train_vec, y_train)

y_pred = model.predict(X_test_vec)

from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

plt.figure()
sns.heatmap(cm, annot=True, fmt='d')
plt.show()

import pickle

pickle.dump(model, open("model.pkl", "wb"))
pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pickle
# 
# # Load model and vectorizer
# model = pickle.load(open("model.pkl", "rb"))
# vectorizer = pickle.load(open("vectorizer.pkl", "rb"))
# 
# # Title
# st.title("🎫 IT Support Ticket Classifier")
# 
# st.write("Enter your issue below and get predicted category")
# 
# # Input box
# user_input = st.text_area("Enter Ticket Text")
# 
# # Predict button
# if st.button("Predict"):
#     if user_input.strip() != "":
#         vectorized_input = vectorizer.transform([user_input])
#         prediction = model.predict(vectorized_input)
# 
#         st.success(f"Predicted Category: {prediction[0]}")
#     else:
#         st.warning("Please enter some text")

